### PR TITLE
masync: suppres unused parameters in future.h

### PR DESCRIPTION
**Pull request by lplewa**
This change is [Reviewable](https://reviewable.io/reviews/pmem/miniasync/110)

### CODE REVIEW

**Comment by kswiecicki** [comment]
:lgtm:

**Comment by lplewa** [comment]
Well, I do not want to use it. This is a public header, and I don't want to include a huge set of suppression macros in it.

**Review by kswiecicki — APPROVED** [review]
Sure, makes sense.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/110#-:-N9aqTmC2Cjqzxbsf-J9:bygtg6h)* status: all files reviewed, 2 unresolved discussions (waiting on @lplewa)

___
*[`src/include/libminiasync/future.h` line 381 at r2](https://reviewable.io/reviews/pmem/miniasync/110#-N9aqP5yAT3PnhS2Lc7s:-N9aqP5yAT3PnhS2Lc7t:b8ornay) ([raw file](https://github.com/pmem/miniasync/blob/11fddd4408850de9854df21f91af2f8cb2e49e8a/src/include/libminiasync/future.h#L381)):*
> ```objc
> future_has_property_default(void *future, enum future_property property)
> {
> 	/* suppres unused parameters */
> ```

suppress



_Code quote:_
```objc
/* suppres unused parameters */
```

**Review by blazej-smorawski — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/110#-:-N9arb0n693JD_Kby91X:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @lplewa)

**Pull request merged**
