### PR TITLE
masync: cleanup vdm abstraction to be more extensible 

### PR DESCRIPTION
**Pull request by pbalcer**
This change generalizes the virtual data mover to support
a generic operation, making it easier to extend the API.
The new abstraction also enables mover implementations
to define their own data structures for operations, which
declutters the future structure.

This is patch 1 of 2. The second patch will implement a
thread-local pool of operations for VDMs, allowing us to
avoid a malloc call on operation_new in all the movers.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/miniasync/43)

### CODE REVIEW

**Review by blazej-smorawski — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/43)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski and @pbalcer)

___
*[src/include/libminiasync/vdm.h, line 66 at r1](https://reviewable.io/reviews/pmem/miniasync/43#-Mv3VXai1L2XJhphfQPf:-Mv3VXai1L2XJhphfQPg:bosb4zl) ([raw file](https://github.com/pmem/miniasync/blob/7ac437f983ea4040fe0479b1abcb9508252bf202/src/include/libminiasync/vdm.h#L66)):*
> ```objc
> struct vdm_operation_data {
> 	struct vdm *vdm;
> 	int64_t id;
> ```

Why is the `id` an `int64` while it's used mostly as a pointer? Is it associated with the upcoming patch? Also, the name `struct vdm_operation_data` is quite confusing for me because there already is the `struct vdm_operation` and they both sound almost the same to me. What do you think about something like `vdm_operation_future_data`? It's quite long but easier to understand I think.

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/43)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski)

___
*[src/include/libminiasync/vdm.h, line 66 at r1](https://reviewable.io/reviews/pmem/miniasync/43#-Mv3VXai1L2XJhphfQPf:-Mv3bi9W0PoLgX0oBsVr:bz9m2n6) ([raw file](https://github.com/pmem/miniasync/blob/7ac437f983ea4040fe0479b1abcb9508252bf202/src/include/libminiasync/vdm.h#L66)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

Why is the `id` an `int64` while it's used mostly as a pointer? Is it associated with the upcoming patch? Also, the name `struct vdm_operation_data` is quite confusing for me because there already is the `struct vdm_operation` and they both sound almost the same to me. What do you think about something like `vdm_operation_future_data`? It's quite long but easier to understand I think.
</blockquote></details>

What is a pointer but an identifier of a memory location in a process? The idea is to have an abstract unique representation of a concrete operation within a vdm. The implementation can be anything. For now, I'm calling malloc everywhere, but the idea is to create a thread-local ring buffer of operations, where we literally just index an array.

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/43)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski)

___
*[src/include/libminiasync/vdm.h, line 66 at r1](https://reviewable.io/reviews/pmem/miniasync/43#-Mv3VXai1L2XJhphfQPf:-Mv3gdz1BWjnJjkRqW9B:b-9uucwv) ([raw file](https://github.com/pmem/miniasync/blob/7ac437f983ea4040fe0479b1abcb9508252bf202/src/include/libminiasync/vdm.h#L66)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

What is a pointer but an identifier of a memory location in a process? The idea is to have an abstract unique representation of a concrete operation within a vdm. The implementation can be anything. For now, I'm calling malloc everywhere, but the idea is to create a thread-local ring buffer of operations, where we literally just index an array.
</blockquote></details>

And yea, the names are not ideal. But I'm following the naming scheme I set everywhere else for future-related variables. I'll try to think of something better.

**Comment by kswiecicki** [comment]
___
*[extras/dml/vdm_dml.c, line 197 at r9](https://reviewable.io/reviews/pmem/miniasync/43#-MvsPg5M57CSO0cOk0Cp:-MvsPg5M57CSO0cOk0Cq:b-79heg3) ([raw file](https://github.com/pmem/miniasync/blob/1acef43fe62ee9292c12567a7ffecb47079773ba/extras/dml/vdm_dml.c#L197)):*
> ```C
> 
> /*
>  * vdm_dml_membuf_size -- returns the size of a job size
> ```

Second 'size' is redundant.



_Code quote:_
```C
returns the size of a job size
```

**Comment by kswiecicki** [comment]
___
*[src/vdm_threads.c, line 60 at r10](https://reviewable.io/reviews/pmem/miniasync/43#-MvwVkyJBq_58L_tNJgC:-MvwVkyJBq_58L_tNJgD:bngmxxb) ([raw file](https://github.com/pmem/miniasync/blob/010a8aa8488a1f5e31c1c41f9239fc17e64b8339/src/vdm_threads.c#L60)):*
> ```C
> 
> /*
>  * vdm_threads_fini -- loop that is executed by every worker
> ```

vdm_threads_loop



_Code quote:_
```C
vdm_threads_fini 
```

**Comment by kswiecicki** [comment]
___
*[extras/dml/vdm_dml.c, line 95 at r10](https://reviewable.io/reviews/pmem/miniasync/43#-MvwYXqv77pcXAS3QF-q:-MvwYXqv77pcXAS3QF-r:b6hzs0b) ([raw file](https://github.com/pmem/miniasync/blob/010a8aa8488a1f5e31c1c41f9239fc17e64b8339/extras/dml/vdm_dml.c#L95)):*
> ```C
> {
> 	dml_finalize_job(*dml_job);
> 	free(*dml_job);
> ```

Since dml_jobs are allocated with ```membuf_alloc()``` should they be free'd?
I was thinking that the membuf automatically reuses the allocated space when the provided ```vdm_dml_membuf_check()``` function returns ```MEMBUF_PTR_CAN_REUSE```.



_Code quote:_
```C
free(*dml_job);
```

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/43)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski and @kswiecicki)

___
*[extras/dml/vdm_dml.c, line 197 at r9](https://reviewable.io/reviews/pmem/miniasync/43#-MvsPg5M57CSO0cOk0Cp:-MvwbYM8Be5xq15OGdvg:bb6un1j) ([raw file](https://github.com/pmem/miniasync/blob/1acef43fe62ee9292c12567a7ffecb47079773ba/extras/dml/vdm_dml.c#L197)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

Second 'size' is redundant.
</blockquote></details>

Done
___
*[extras/dml/vdm_dml.c, line 95 at r10](https://reviewable.io/reviews/pmem/miniasync/43#-MvwYXqv77pcXAS3QF-q:-MvwbGjaEKR29swjpSyu:b-v9o5w0) ([raw file](https://github.com/pmem/miniasync/blob/010a8aa8488a1f5e31c1c41f9239fc17e64b8339/extras/dml/vdm_dml.c#L95)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

Since dml_jobs are allocated with ```membuf_alloc()``` should they be free'd?
I was thinking that the membuf automatically reuses the allocated space when the provided ```vdm_dml_membuf_check()``` function returns ```MEMBUF_PTR_CAN_REUSE```.
</blockquote></details>

No, you are right. I haven't tested this code /w DML.
Done.
___
*[src/vdm_threads.c, line 60 at r10](https://reviewable.io/reviews/pmem/miniasync/43#-MvwVkyJBq_58L_tNJgC:-MvwbZnH6jUHxBErKNZU:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/010a8aa8488a1f5e31c1c41f9239fc17e64b8339/src/vdm_threads.c#L60)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

vdm_threads_loop
</blockquote></details>

Done.
___
*[src/include/libminiasync/vdm.h, line 66 at r1](https://reviewable.io/reviews/pmem/miniasync/43#-Mv3VXai1L2XJhphfQPf:-MvwbfNq6QFzgdWXdHax:b7qhpwt) ([raw file](https://github.com/pmem/miniasync/blob/7ac437f983ea4040fe0479b1abcb9508252bf202/src/include/libminiasync/vdm.h#L66)):*
<details><summary><i>Previously, blazej-smorawski wrote…</i></summary><blockquote>

OK, makes sense now. 
</blockquote></details>

I've now changed the id to a `void *` pointer and changed the names slightly.

**Comment by kswiecicki** [comment]
:lgtm:

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/43)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @lplewa)

___
*[src/include/libminiasync/vdm.h, line 86 at r11](https://reviewable.io/reviews/pmem/miniasync/43#-MvyVDd10jcpf_Szkeih:-Mw1uT3F2r2P4H4ZsY5w:bkln7yd) ([raw file](https://github.com/pmem/miniasync/blob/5e8943f4eb45d86ae97de761f64e9263d68f7fa8/src/include/libminiasync/vdm.h#L86)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

Maybe not a part of the pull request, but you are changing names anyway ;)

Move those functions and their implementation to a separate file (mover_synchronus.c)
Do the exact change for the entire vdm_threads.h

VDM is an "abstract virtual data mover" where these interface implementations are no longer abstract nor virtual and should name as a "data mover".

Consider moving ``vdm_memcpy`` function to the vdm_operations.h, and so renaming vdm.c so vdm.h will become "struct only", and we will have a much cleaner abstraction for PMDK (and other libraries which want only to provide an implementation of vdm structure)
</blockquote></details>

I changed the names and moved sync to its own file. But I didn't move the content of vdm.c to the header. I'm not sure if we need to do that. It should be possible now to use vdm inside of libpmem2 without pulling in the runtime dependency.

**Review by lplewa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/43#-:-Mw6yj334ITh8hdVccHl:bnfp4nl)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @blazej-smorawski, @kswiecicki, and @lplewa)

**Pull request merged**
