### PR TITLE
masync: replace {0} with proper initialisation

### PR DESCRIPTION
**Pull request by lplewa**
This change is [Reviewable](https://reviewable.io/reviews/pmem/miniasync/76)

### CODE REVIEW

**Review by kswiecicki — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/76)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lplewa)

**Review by DamianDuy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/76#-:-Mznxx2n7CFHR2lB1CrV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lplewa)

**Review by pbalcer — COMMENTED** [review]
did you check if this works with a C++ compiler?

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/76#-:-Mzo9fvM8C2YvEnJzoAY:b467rye)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lplewa)

**Review by lplewa — COMMENTED** [review]
To make it work with c++ it's a different change. 

c++ doesn't support any .field= initialisation list. You have to use or "nameless" initialisation (i.e. {0,0,0,0}), or do not use initialiser list at all. 

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/76#-:-MzoDVMP4Efd05oFKDC6:bomw7yb)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lplewa)

**Review by lplewa — COMMENTED** [review]
Now it works

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/76#-:-MzoJPtj6Dm8QgJ81M8F:b-n5c41e)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @kswiecicki)

**Review by pbalcer — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/76#-:-MzoWErSA4eCmAgGm2m0:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @kswiecicki)

**Pull request merged**
