### PR TITLE
masync: add macro to check if chain entry was initialized

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] not sure if I should describe that in some docs...? if you even consider merging this... 😉

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/miniasync/92)

### CODE REVIEW

**Comment by kswiecicki** [comment]
Future macros should be described in `miniasync_future.7.md`.

**Comment by lukaszstolarczuk** [comment]
Yeah, but the real question is - do you consider merging this, and if it should be public? 😉

**Comment by lukaszstolarczuk** [comment]
ok, done - described in manpage.

**Comment by kswiecicki** [comment]
Could you add a test case with a normal future initialization?

**Comment by kswiecicki** [comment]
:lgtm:

**Review by lukaszstolarczuk — COMMENTED** [review]
> Could you add a test case with a normal future initialization?
sure thing, done.

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/92#-:-N2vTe8J5i_OeQja0qzx:bbtid10)* status: 0 of 3 files reviewed, all discussions resolved

**Pull request merged**
