### PR TITLE
common: replace functions from stdatomic with wrappers

### PR DESCRIPTION
**Pull request by DamianDuy**
This change is [Reviewable](https://reviewable.io/reviews/pmem/miniasync/32)

### CODE REVIEW

**Comment by kswiecicki** [comment]
I assume we'll add the 'core' build on Windows in different PR not to clutter this one?

**Comment by pbalcer** [comment]
Do we actually need all these things? If we merge this it will show up as mostly dead code probably.

**Review by wlemkows — COMMENTED** [review]
@pbalcer I'm guessing that we do not need all functions, but all files, we may also remove unused functions, but some may be useful in the future.
The question is how to decide what to remove and what not...

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/32#-:-Mr6k_js8oDCf56MLcM0:b-colwa0)* status: 0 of 15 files reviewed, all discussions resolved

**Comment by pbalcer** [comment]
I suggest we merge it as-is and then, before release, prune unused code based on code coverage info.

**Review by wlemkows — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/32#-:-Mr6ndOcBNvF7b4TOIZ8:bnfp4nl)* status: 0 of 15 files reviewed, all discussions resolved

**Comment by kswiecicki** [comment]
:lgtm:

**Pull request merged**
