### PR TITLE
doc: add CMakeLists file to the man pages

### PR DESCRIPTION
**Pull request by wlemkows**
This change is [Reviewable](https://reviewable.io/reviews/pmem/miniasync/26)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/26)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[CMakeLists.txt, line 16 at r1](https://reviewable.io/reviews/pmem/miniasync/26#-MqJFWyT0ssueOTjQJm5:-MqJFWyT0ssueOTjQJm6:b-s98rb6) ([raw file](https://github.com/pmem/miniasync/blob/552af9c1a6a47b5800f1879bcc40ea8a5104067e/CMakeLists.txt#L16)):*
> ```CMake
> set(VERSION ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH})
> 
> set(MINIASYNC_SOURCE_DIR ${CMAKE_SOURCE_DIR}/src)
> ```

you can use here the new ROOT_DIR variable

in general, we introduced that ROOT_DIR variable, because if you use our CMake within another CMake project then "CMAKE_SOURCE_DIR" will point to that another CMake's dir
___
*[CMakeLists.txt, line 25 at r1](https://reviewable.io/reviews/pmem/miniasync/26#-MqJG4cR-kZeVlFqU5yj:-MqJG4cR-kZeVlFqU5yk:bak9va0) ([raw file](https://github.com/pmem/miniasync/blob/552af9c1a6a47b5800f1879bcc40ea8a5104067e/CMakeLists.txt#L25)):*
> ```CMake
> option(USE_ASAN "enable AddressSanitizer (debugging)" OFF)
> option(USE_UBSAN "enable UndefinedBehaviorSanitizer (debugging)" OFF)
> option(BUILD_DOC "build documentation" ON)
> ```

you can put all these options together somehow :wink: (below are for examples and tests)
___
*[doc/CMakeLists.txt, line 89 at r1](https://reviewable.io/reviews/pmem/miniasync/26#-MqJGVbW5ACyPZFqnZSw:-MqJGVbW5ACyPZFqnZSx:bvl91fh) ([raw file](https://github.com/pmem/miniasync/blob/552af9c1a6a47b5800f1879bcc40ea8a5104067e/doc/CMakeLists.txt#L89)):*
> ```CMake
> ## Prepare the actual 'make doc' command
> # ----------------------------------------------------------------- #
> if(MANPAGE_OUTFILES OR DOXYGEN_COMMAND)
> ```

AFAIK, you don't have any doxygen command (unless you plan to build it later on.

IMHO, this whole section is redundant, because it can be done within the "if(PANDOC)" section above

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/26)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @wlemkows)

___
*[doc/CMakeLists.txt, line 47 at r1](https://reviewable.io/reviews/pmem/miniasync/26#-MqJLqIO4vHTZ4-S6izn:-MqJLqIPD5F_xlDE6zXR:b-248s9y) ([raw file](https://github.com/pmem/miniasync/blob/552af9c1a6a47b5800f1879bcc40ea8a5104067e/doc/CMakeLists.txt#L47)):*
> ```CMake
> 	## Manpages without any examples
> 	# miniasync.7
> 	configure_file(${CMAKE_CURRENT_SOURCE_DIR}/miniasync.7.md.in
> ```

FYI, I just looked into your manpages and am not sure if you need these `configure_file` calls

CMake's configure_file function is used to replace e.g. `@variables@` in build time, e.g. with current VERSION or (as in pmemkv's case) dynamically input EXAMPLE into the manpage (instead of copy-pasting it).

**Review by wlemkows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/26)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[CMakeLists.txt, line 16 at r1](https://reviewable.io/reviews/pmem/miniasync/26#-MqJFWyT0ssueOTjQJm5:-MqYLYZo-ynotOfuNYFP:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/552af9c1a6a47b5800f1879bcc40ea8a5104067e/CMakeLists.txt#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can use here the new ROOT_DIR variable

in general, we introduced that ROOT_DIR variable, because if you use our CMake within another CMake project then "CMAKE_SOURCE_DIR" will point to that another CMake's dir
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 25 at r1](https://reviewable.io/reviews/pmem/miniasync/26#-MqJG4cR-kZeVlFqU5yj:-MqYMNq46kJZUADDvjei:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/552af9c1a6a47b5800f1879bcc40ea8a5104067e/CMakeLists.txt#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can put all these options together somehow :wink: (below are for examples and tests)
</blockquote></details>

Done.
___
*[doc/CMakeLists.txt, line 47 at r1](https://reviewable.io/reviews/pmem/miniasync/26#-MqJLqIO4vHTZ4-S6izn:-MqYPp5A4mjXUdo0Co34:bqva0r9) ([raw file](https://github.com/pmem/miniasync/blob/552af9c1a6a47b5800f1879bcc40ea8a5104067e/doc/CMakeLists.txt#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

FYI, I just looked into your manpages and am not sure if you need these `configure_file` calls

CMake's configure_file function is used to replace e.g. `@variables@` in build time, e.g. with current VERSION or (as in pmemkv's case) dynamically input EXAMPLE into the manpage (instead of copy-pasting it).
</blockquote></details>

We are not using variables at this point, but we don't know whether or not we will use them in the future.
(also for examples)
___
*[doc/CMakeLists.txt, line 89 at r1](https://reviewable.io/reviews/pmem/miniasync/26#-MqJGVbW5ACyPZFqnZSw:-MqYcOlM6NJsk2ApT_uw:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/552af9c1a6a47b5800f1879bcc40ea8a5104067e/doc/CMakeLists.txt#L89)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

AFAIK, you don't have any doxygen command (unless you plan to build it later on.

IMHO, this whole section is redundant, because it can be done within the "if(PANDOC)" section above
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:+1: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/26#-:-MqYjLIjAm2_GC7jwv4t:b-8fx2u7)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @wlemkows)

**Review by pbalcer — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/26#-:-MqZOuQZEuZd1n3GneP5:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
