### PR TITLE
masync: rename mover to vdm (virtual data mover)

### PR DESCRIPTION
**Pull request by pbalcer**
This helps make the purpose of the mover/vdm interface more obvious.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/miniasync/14)

### CODE REVIEW

**Comment by pbalcer** [comment]
I'm not sure about this name, but I guess it's more descriptive then just plain "mover" and "mover runner"

**Review by DamianDuy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/14#-:-MpeuT6r78upooJSaYEt:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved

**Review by lplewa — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/14#-:-MpgNOu93RKS-2gIUFXd:bnfp4nl)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @lplewa)

**Review by lplewa — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pbalcer)

**Pull request merged**
