### PR TITLE
masync: add memmove operation to the thread data mover

### PR DESCRIPTION
**Pull request by DamianDuy**
This change is [Reviewable](https://reviewable.io/reviews/pmem/miniasync/77)

### CODE REVIEW

**Review by pbalcer — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/77#-:-MzoA4g50f2p7AF0oEZf:bnfp4nl)* status: 0 of 18 files reviewed, all discussions resolved

**Review by lplewa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/77)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @DamianDuy and @lplewa)

___
*[tests/memmove_threads/memmove_threads.c, line 65 at r1](https://reviewable.io/reviews/pmem/miniasync/77#-MzoFpCa9wgRQKVhEn_O:-MzoFpCa9wgRQKVhEn_P:b48byt8) ([raw file](https://github.com/pmem/miniasync/blob/767adf3cba1930a5fe8bc3375856225b9a03db05/tests/memmove_threads/memmove_threads.c#L65)):*
> ```C
> {
> 	int ret = 0;
> 	unsigned seed = (unsigned)time(NULL);
> ```

please log seed (especially in case of error)

**Review by blazej-smorawski — COMMENTED** [review]
:lgtm: 

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/77#-:-Mztlrlp6uQuKUjhc6AY:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @DamianDuy)

**Comment by wlemkows** [comment]
Please rebase

**Review by DamianDuy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/77)* status: 6 of 18 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski and @lplewa)

___
*[tests/memmove_threads/memmove_threads.c, line 65 at r1](https://reviewable.io/reviews/pmem/miniasync/77#-MzoFpCa9wgRQKVhEn_O:-N-1vgz0CChigu1zXTuQ:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/767adf3cba1930a5fe8bc3375856225b9a03db05/tests/memmove_threads/memmove_threads.c#L65)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

please log seed (especially in case of error)
</blockquote></details>

Done.

**Comment by wlemkows** [comment]
I think something is wrong with the commits in this PR.

**Review by wlemkows — COMMENTED** [review]
> Reviewed 2 of 18 files at r1, 11 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/77)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski and @lplewa)

**Review by DamianDuy — COMMENTED** [review]
Yes. I messed up the commits when I was rebasing but I removed the redundant ones now. 

> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/77#-:-N-77pWF5c452sFL0LJ0:btbwetu)* status: 16 of 18 files reviewed, all discussions resolved (waiting on @blazej-smorawski and @wlemkows)

**Review by wlemkows — COMMENTED** [review]
> Reviewed 1 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/77)* status: 16 of 18 files reviewed, all discussions resolved (waiting on @blazej-smorawski and @wlemkows)

**Review by wlemkows — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/77)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @DamianDuy)

**Review by wlemkows — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamianDuy)

**Pull request merged**
