### PR TITLE
masync: add flush operation for DML data mover

### PR DESCRIPTION
**Pull request by DamianDuy**
---
This change is [Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)

### CODE REVIEW

**Comment by kswiecicki** [comment]
*[`src/include/libminiasync/vdm.h` line 108 at r1](https://reviewable.io/reviews/pmem/miniasync/90#-N1hxfkN1mS0AXhyzUAS:-N1hxfkR8-adsCVYjZky:b-31u9n7) ([raw file](https://github.com/pmem/miniasync/blob/37925c528f31fd4b4bfa331e8bcd86eadea03b90/src/include/libminiasync/vdm.h#L108)):*
> ```objc
> /* I'm not sure what the output of this op should be */
> struct vdm_operation_output_flush {
> 	void *dest;
> ```

I would set the output to be the same as the return value of the `pmem2_flush_fn` type in libpmem2, that is `void`.



_Code quote:_
```objc
struct vdm_operation_output_flush {
	void *dest;
};
```

**Review by DamianDuy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @kswiecicki)

___
*[`src/include/libminiasync/vdm.h` line 108 at r1](https://reviewable.io/reviews/pmem/miniasync/90#-N1hxfkN1mS0AXhyzUAS:-N1rbhHo-r2uC9d7Bnin:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/37925c528f31fd4b4bfa331e8bcd86eadea03b90/src/include/libminiasync/vdm.h#L108)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

I would set the output to be the same as the return value of the `pmem2_flush_fn` type in libpmem2, that is `void`.
</blockquote></details>

Done.
___
*[`tests/data_mover_dml_flush/test_data_mover_dml_flush.cmake` line 4 at r1](https://reviewable.io/reviews/pmem/miniasync/90#-N1hzTMaB4uzT5FgqUv8:-N1rbj7ADa66VCXE1yPv:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/37925c528f31fd4b4bfa331e8bcd86eadea03b90/tests/data_mover_dml_flush/test_data_mover_dml_flush.cmake#L4)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

I just noticed that we have several `.cmake` files that begin with the comment `# an example for the ...`, but they are not examples but genuine test cases.
We could use a more descriptive comment for those and leave only `test_dummy.cmake` as is.
</blockquote></details>

Done.

**Comment by kswiecicki** [comment]
*[`doc/data_mover_dml_get_vdm.3.md` line 58 at r2](https://reviewable.io/reviews/pmem/miniasync/90#-N1s7g856TlGacPDXvW2:-N1s7g86-bkw4zDkn0ku:b6s09hj) ([raw file](https://github.com/pmem/miniasync/blob/dfbd9bf359a6070a41e5da858981add506dae048/doc/data_mover_dml_get_vdm.3.md#L58)):*
> ```Markdown
> # SEE ALSO #
> 
> **vdm_memcpy**(3), **vdm_memmove**(3), **vdm_memset**(3), **vdm_flush**(3),
> ```

We sort the function mentions alphabetically and in regards to manpage number suffix.
Here we split (3), and (7) manpages and ordered them alphabetically in their groups.



_Code quote:_
```Markdown
**vdm_flush**(3),
```

**Review by kswiecicki — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 5 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)* status: 9 of 27 files reviewed, 4 unresolved discussions (waiting on @DamianDuy and @kswiecicki)

___
*[`doc/miniasync_vdm.7.md` line 131 at r2](https://reviewable.io/reviews/pmem/miniasync/90#-N1s8cgI0RuPKjZpmEd_:-N1s8cgI0RuPKjZpmEda:b3kqx) ([raw file](https://github.com/pmem/miniasync/blob/dfbd9bf359a6070a41e5da858981add506dae048/doc/miniasync_vdm.7.md#L131)):*
> ```Markdown
> # SEE ALSO #
> 
> **vdm_memcpy**(3), **vdm_memmove**(3), **vdm_memset**(3), **vdm_flush**(3),
> ```

.



_Code quote:_
```Markdown
**vdm_flush**(3),
```
___
*[`doc/miniasync_vdm_dml.7.md` line 86 at r2](https://reviewable.io/reviews/pmem/miniasync/90#-N1s8goo4vweWevQES2q:-N1s8goo4vweWevQES2r:bka5mr7) ([raw file](https://github.com/pmem/miniasync/blob/dfbd9bf359a6070a41e5da858981add506dae048/doc/miniasync_vdm_dml.7.md#L86)):*
> ```Markdown
> 
> **data_mover_dml_new**(3), **data_mover_dml_get_vdm**(3),
> **vdm_memcpy**(3), **vdm_memmove**(3), **vdm_memset**(3),
> ```

Mention flush here too.



_Code quote:_
```Markdown
**vdm_memcpy**(3), **vdm_memmove**(3), **vdm_memset**(3),
```

**Review by DamianDuy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)* status: 4 of 27 files reviewed, 4 unresolved discussions (waiting on @kswiecicki)

___
*[`doc/data_mover_dml_get_vdm.3.md` line 58 at r2](https://reviewable.io/reviews/pmem/miniasync/90#-N1s7g856TlGacPDXvW2:-N1wIZyRAcfj8IA33p9b:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/dfbd9bf359a6070a41e5da858981add506dae048/doc/data_mover_dml_get_vdm.3.md#L58)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

We sort the function mentions alphabetically and in regards to manpage number suffix.
Here we split (3), and (7) manpages and ordered them alphabetically in their groups.
</blockquote></details>

Done.
___
*[`doc/miniasync_vdm.7.md` line 131 at r2](https://reviewable.io/reviews/pmem/miniasync/90#-N1s8cgI0RuPKjZpmEd_:-N1wI_oz8gi2YbhhWate:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/dfbd9bf359a6070a41e5da858981add506dae048/doc/miniasync_vdm.7.md#L131)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`doc/miniasync_vdm_dml.7.md` line 86 at r2](https://reviewable.io/reviews/pmem/miniasync/90#-N1s8goo4vweWevQES2q:-N1wIaYtBcpB4nRx_LlU:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/dfbd9bf359a6070a41e5da858981add506dae048/doc/miniasync_vdm_dml.7.md#L86)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

Mention flush here too.
</blockquote></details>

Done.

**Review by pbalcer — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)* status: 5 of 27 files reviewed, 6 unresolved discussions (waiting on @DamianDuy, @kswiecicki, and @pbalcer)

___
*[`doc/vdm_memmove.3.md` line 34 at r3](https://reviewable.io/reviews/pmem/miniasync/90#-N3JtU3gDYuEl4_Mpwh-:-N3JtU3gDYuEl4_Mpwh0:bebk4pz) ([raw file](https://github.com/pmem/miniasync/blob/41a2b2222fee3743988e12507ca3dab04d6925f1/doc/vdm_memmove.3.md#L34)):*
> ```Markdown
> 	VDM_OPERATION_MEMMOVE,
> 	VDM_OPERATION_MEMSET,
> 	VDM_FLUSH,
> ```

VDM_OPERATION_FLUSH
___
*[`doc/vdm_memset.3.md` line 34 at r3](https://reviewable.io/reviews/pmem/miniasync/90#-N3JtqLR5BKSaxdNN7z6:-N3JtqLR5BKSaxdNN7z7:bmzue0q) ([raw file](https://github.com/pmem/miniasync/blob/41a2b2222fee3743988e12507ca3dab04d6925f1/doc/vdm_memset.3.md#L34)):*
> ```Markdown
> 	VDM_OPERATION_MEMMOVE,
> 	VDM_OPERATION_MEMSET,
> 	VDM_FLUSH,
> ```

ditto

(btw - do we really need this enum copy pasted everywhere?)

**Review by DamianDuy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)* status: 4 of 27 files reviewed, 6 unresolved discussions (waiting on @DamianDuy, @kswiecicki, and @pbalcer)

___
*[`doc/vdm_memset.3.md` line 34 at r3](https://reviewable.io/reviews/pmem/miniasync/90#-N3JtqLR5BKSaxdNN7z6:-N3T8WLD1Knjua4F-l1d:b-pumnav) ([raw file](https://github.com/pmem/miniasync/blob/41a2b2222fee3743988e12507ca3dab04d6925f1/doc/vdm_memset.3.md#L34)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

ditto

(btw - do we really need this enum copy pasted everywhere?)
</blockquote></details>

I think we don't really need it so I've deleted it from the vdm operations man pages and only left in the miniasync_vdm man page.

**Comment by kswiecicki** [comment]
*[`extras/dml/data_mover_dml.c` line 15 at r5](https://reviewable.io/reviews/pmem/miniasync/90#-N6N3HJv7wLKkDlIrTR5:-N6N3HJv7wLKkDlIrTR6:bfqwkml) ([raw file](https://github.com/pmem/miniasync/blob/154c1118d292d75cbf541433108138ee7c3c5961/extras/dml/data_mover_dml.c#L15)):*
> ```C
> #define SUPPORTED_FLAGS VDM_F_MEM_DURABLE \
> 						| VDM_F_NO_CACHE_HINT \
> 						| VDM_F_DONT_INVALIDATE_CACHE
> ```

Due to the issue that @pbalcer mentioned today, we can't use `VDM_F_MEM_DURABLE` in conjunction with `VDM_F_DONT_INVALIDATE_CACHE`.
We should return an error when those two flags use together or flatly ignore the `VDM_F_DONT_INVALIDATE_CACHE` flag when `VDM_F_MEM_DURABLE` is used.



_Code quote:_
```C
#define SUPPORTED_FLAGS VDM_F_MEM_DURABLE \
						| VDM_F_NO_CACHE_HINT \
						| VDM_F_DONT_INVALIDATE_CACHE
```

**Review by pbalcer — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)* status: 5 of 27 files reviewed, 9 unresolved discussions (waiting on @blazej-smorawski, @DamianDuy, @kswiecicki, @lplewa, @pbalcer, and @wlemkows)

___
*[`doc/miniasync_vdm_dml.7.md` line 59 at r5](https://reviewable.io/reviews/pmem/miniasync/90#-N6N5Dqk1aKdukeNcGWy:-N6N5Dqk1aKdukeNcGWz:bgokw0) ([raw file](https://github.com/pmem/miniasync/blob/154c1118d292d75cbf541433108138ee7c3c5961/doc/miniasync_vdm_dml.7.md#L59)):*
> ```Markdown
> 
> * **VDM_F_MEM_DURABLE** - write to destination is identified as write to durable memory
> * **VDM_F_DONT_INVALIDATE_CACHE** - do not evict affected cache lines from caches during
> ```

if possible, do not evict ... There's no guarantee that the flushed data will remain in the cache.
___
*[`doc/vdm_flush.3.md` line 46 at r5](https://reviewable.io/reviews/pmem/miniasync/90#-N6N5fQv6_7ZsTa0ICsY:-N6N5fQv6_7ZsTa0ICsZ:b-5i298o) ([raw file](https://github.com/pmem/miniasync/blob/154c1118d292d75cbf541433108138ee7c3c5961/doc/vdm_flush.3.md#L46)):*
> ```Markdown
> **vdm_flush**() initializes and returns a new flush future based on the virtual data mover
> implementation instance *vdm*. The parameters: *dest*, *n* are standard flush parameters.
> The *flags* represents data mover specific flags. The **VDM_F_DONT_INVALIDATE_CACHE** specifies
> ```

DONT_INVALIDATE_CACHE is a hint that signals the hardware to avoid invalidating the cache lines if possible.
___
*[`extras/dml/data_mover_dml.c` line 15 at r5](https://reviewable.io/reviews/pmem/miniasync/90#-N6N3HJv7wLKkDlIrTR5:-N6N6BE09GVaULoyCN4P:b9fqi5t) ([raw file](https://github.com/pmem/miniasync/blob/154c1118d292d75cbf541433108138ee7c3c5961/extras/dml/data_mover_dml.c#L15)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

Due to the issue that @pbalcer mentioned today, we can't use `VDM_F_MEM_DURABLE` in conjunction with `VDM_F_DONT_INVALIDATE_CACHE`.
We should return an error when those two flags use together or flatly ignore the `VDM_F_DONT_INVALIDATE_CACHE` flag when `VDM_F_MEM_DURABLE` is used.
</blockquote></details>

:+1: let's just ignore that flag for dml.

**Review by DamianDuy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)* status: 5 of 27 files reviewed, 9 unresolved discussions (waiting on @blazej-smorawski, @DamianDuy, @kswiecicki, @lplewa, @pbalcer, and @wlemkows)

___
*[`doc/miniasync_vdm_dml.7.md` line 59 at r5](https://reviewable.io/reviews/pmem/miniasync/90#-N6N5Dqk1aKdukeNcGWy:-N6RsrPk60ZB3vAesSpF:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/154c1118d292d75cbf541433108138ee7c3c5961/doc/miniasync_vdm_dml.7.md#L59)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

if possible, do not evict ... There's no guarantee that the flushed data will remain in the cache.
</blockquote></details>

Done.
___
*[`doc/vdm_flush.3.md` line 46 at r5](https://reviewable.io/reviews/pmem/miniasync/90#-N6N5fQv6_7ZsTa0ICsY:-N6RssVk5biGAEZYG4gW:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/154c1118d292d75cbf541433108138ee7c3c5961/doc/vdm_flush.3.md#L46)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

DONT_INVALIDATE_CACHE is a hint that signals the hardware to avoid invalidating the cache lines if possible.
</blockquote></details>

Done.
___
*[`extras/dml/data_mover_dml.c` line 15 at r5](https://reviewable.io/reviews/pmem/miniasync/90#-N6N3HJv7wLKkDlIrTR5:-N6Rt11dCxHjHVDR8I1Y:b-896fix) ([raw file](https://github.com/pmem/miniasync/blob/154c1118d292d75cbf541433108138ee7c3c5961/extras/dml/data_mover_dml.c#L15)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

:+1: let's just ignore that flag for dml.
</blockquote></details>

Done.

**Review by pbalcer — COMMENTED** [review]
> Reviewed 1 of 9 files at r3, 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)* status: 7 of 27 files reviewed, 6 unresolved discussions (waiting on @blazej-smorawski, @DamianDuy, @kswiecicki, @lplewa, and @wlemkows)

**Comment by DamianDuy** [comment]
I removed the ```VDM_F_DONT_INVALIDATE_CACHE``` flag.

**Review by kswiecicki — CHANGES_REQUESTED** [review]
> Reviewed 14 of 23 files at r2, 9 of 9 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)* status: all files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski, @DamianDuy, @lplewa, and @wlemkows)

___
*[`extras/dml/data_mover_dml.c` line 43 at r7](https://reviewable.io/reviews/pmem/miniasync/90#-N7V3bEw0HzVq8mKb0Wa:-N7V3bExCbCseFh2EWv_:btw3zcg) ([raw file](https://github.com/pmem/miniasync/blob/ce33a9abefa9a2e7db8c5142fa97a768e9025a3d/extras/dml/data_mover_dml.c#L43)):*
> ```C
> 				break;
> 			case VDM_F_NO_CACHE_HINT:
> 				*dml_flags &= ~DML_FLAG_PREFETCH_CACHE;
> ```

You have removed the `VDM_F_NO_CACHE_HINT` case break so it falls into the default case.



_Code quote:_
```C
			case VDM_F_NO_CACHE_HINT:
				*dml_flags &= ~DML_FLAG_PREFETCH_CACHE;
```

**Review by DamianDuy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)* status: 25 of 27 files reviewed, 2 unresolved discussions (waiting on @blazej-smorawski, @DamianDuy, @kswiecicki, @lplewa, @pbalcer, and @wlemkows)

___
*[`extras/dml/data_mover_dml.c` line 43 at r7](https://reviewable.io/reviews/pmem/miniasync/90#-N7V3bEw0HzVq8mKb0Wa:-N7V5pbFBbtA5IK5lYwi:b7km72c) ([raw file](https://github.com/pmem/miniasync/blob/ce33a9abefa9a2e7db8c5142fa97a768e9025a3d/extras/dml/data_mover_dml.c#L43)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

You have removed the `VDM_F_NO_CACHE_HINT` case break so it falls into the default case.
</blockquote></details>

Done. Thanks for noticing.

**Review by kswiecicki — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/90)* status: all files reviewed, 1 unresolved discussion (waiting on @blazej-smorawski, @DamianDuy, @lplewa, and @wlemkows)

**Pull request merged**
