### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
I started reading your docs and examples and I've encountered a few random, rather small issues.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/miniasync/45)

### CODE REVIEW

**Review by pbalcer — COMMENTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/45)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @pbalcer)

___
*[doc/miniasync_vdm_dml.3.md.in, line 54 at r1](https://reviewable.io/reviews/pmem/miniasync/45#-MvZ5BuC6jhiZsfAnlMp:-Mvch7d4Ca6KFo2k4HQx:b697kb9) ([raw file](https://github.com/pmem/miniasync/blob/4da48d674e9e5875c654cb99d96b3906baf855ee/doc/miniasync_vdm_dml.3.md.in#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure here if `miniasync_vdm_dml` is a proper thingy you wanted to put...? perhaps it should rather be `libminiasync-dml provides`? or something else...? `miniasync_vdm_dml` is just a name of the manpage, if I understand correctly.
</blockquote></details>

+1
libminiasync-dml

**Comment by kswiecicki** [comment]
___
*[doc/miniasync_vdm_dml.3.md.in, line 48 at r1](https://reviewable.io/reviews/pmem/miniasync/45#-MvZ5c2m0Lhu41KqV8fz:-Mvcz78j-HjPRqOXffDA:b5itq7w) ([raw file](https://github.com/pmem/miniasync/blob/4da48d674e9e5875c654cb99d96b3906baf855ee/doc/miniasync_vdm_dml.3.md.in#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Reading this manpage I wasn't sure where the user should set all these flags?
</blockquote></details>

There's an example of flag usage in the # EXAMPLE # section.
You are right, there should be information how to use those flags before or after the *MINIASYNC_DML_F_PATH_HW* flag is mentioned. Possibly we could also point to the example below.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/miniasync/45)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @kswiecicki and @pbalcer)

___
*[doc/miniasync_vdm_dml.3.md.in, line 48 at r1](https://reviewable.io/reviews/pmem/miniasync/45#-MvZ5c2m0Lhu41KqV8fz:-MvdTiXR2c0QwOnv8_BZ:bf07el9) ([raw file](https://github.com/pmem/miniasync/blob/4da48d674e9e5875c654cb99d96b3906baf855ee/doc/miniasync_vdm_dml.3.md.in#L48)):*
<details><summary><i>Previously, kswiecicki (Krzysztof Święcicki) wrote…</i></summary><blockquote>

There's an example of flag usage in the # EXAMPLE # section.
You are right, there should be information how to use those flags before or after the *MINIASYNC_DML_F_PATH_HW* flag is mentioned. Possibly we could also point to the example below.
</blockquote></details>

I've left the XXX for now

**Comment by kswiecicki** [comment]
:lgtm:

**Pull request merged**
